# Generated by Django 5.0.7 on 2024-09-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('prim 1', 'prim 1'), ('prim 2', 'prim 2'), ('prim 3', 'prim 3'), ('prim 4', 'prim 4'), ('prim 5', 'prim 5'), ('prep 1', 'prep 1'), ('prep 2', 'prep 2'), ('prep 3', 'prep 3'), ('prep 4', 'prep 4'), ('sec 1', 'sec 1'), ('sec 2', 'sec 2'), ('sec 3', 'sec 3')], max_length=20)),
                ('cls', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('registered', models.BooleanField(default=False)),
                ('parent_number', models.CharField(max_length=13)),
                ('absence_count', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile')),
            ],
        ),
    ]
