# Generated by Django 5.0.7 on 2024-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12E')], max_length=20),
        ),
    ]
