# Generated by Django 4.2.14 on 2025-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_negative_reports',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_positive_reports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
