# Generated by Django 5.2.3 on 2025-06-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_total_negative_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_negative_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_positive_reports',
            field=models.IntegerField(default=0),
        ),
    ]
