# Generated by Django 4.2.14 on 2025-05-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
