# Generated by Django 5.0.7 on 2024-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_constant_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
