# Generated by Django 5.0.7 on 2024-09-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French'), ('Math', 'Math'), ('Physics', 'Physics')], max_length=50),
        ),
    ]
