# Generated by Django 4.2.14 on 2025-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_teacher_alter_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='total_negative_reports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='total_positive_reports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
