# Generated by Django 5.2.3 on 2025-06-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacher_total_negative_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='total_negative_reports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='total_positive_reports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
