# Generated by Django 4.2.14 on 2025-05-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade'),
        ('teachers', '0007_teacher_teacher_alter_teacher_school'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='teacherreport',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
