# Generated by Django 4.2.14 on 2025-06-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_studentreport_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreport',
            old_name='is_postiive',
            new_name='is_positive',
        ),
        migrations.RenameField(
            model_name='teacherreport',
            old_name='is_postiive',
            new_name='is_positive',
        ),
    ]
